POST http://localhost:3000/api/auth/users/register HTTP/1.1
content-type: application/json

{
   " name": "Ala", 
   "selected": "rider",
   "mobile": "615301501"

}



###


POST http://localhost:3000/api/auth/users/register HTTP/1.1
content-type: application/json

{
   " name": "Asif", 
   "selected": "rider",
   "mobile": "615301502"

}


###


POST http://localhost:3000/api/auth/users/register HTTP/1.1
content-type: application/json

{
   " name": "Suu", 
   "selected": "rider",
   "mobile": "615301503"

}