const roles = [
  {
    name: 'Super Admin',
    description:
      'Super Admins can access and manage all features and settings.',
    type: 'SUPER_ADMIN',
  },
  {
    name: 'Author',
    description: 'Authors can manage the content they have created.',
    type: 'AUTHOR',
  },
  {
    name: 'Editor',
    description:
      'Editors can manage and publish contents including those of other users.',
    type: 'EDITOR',
  },
  {
    name: 'Public',
    description: 'Default role given to unauthenticated user.',
    type: 'PUBLIC',
  },
  {
    name: 'Authenticated',
    description: 'Default role given to authenticated user.',
    type: 'AUTHENTICATED',
  },
]

const users = {
  name: 'Ahmed Ibrahim',
  mobileNumber: 252615301507,
  otp: '123456',
  otpExpire: Date.now() + 10 * (60 * 1000), // Ten Minutes
}

const profile = {
  name: 'Ahmed Ibrahim',
  userType: 'user',
  image: 'https://github.com/ahmaat19.png',
}

const clientPermissions = [
  {
    name: 'Home',
    path: '/',
    menu: 'hidden',
    auth: true,
    description: 'Home page',
  },
  {
    name: 'Users',
    path: '/admin/auth/users',
    menu: 'admin',
    auth: true,
    description: 'Users page',
  },
  {
    name: 'Roles',
    path: '/admin/auth/roles',
    menu: 'admin',
    auth: true,
    description: 'Roles page',
  },
  {
    name: 'Profile',
    path: '/account/profile',
    menu: 'profile',
    auth: true,
    description: 'Profile page',
  },
  {
    name: 'Permissions',
    path: '/admin/auth/permissions',
    menu: 'admin',
    auth: true,
    description: 'Permissions page',
  },
  {
    name: 'Client Permissions',
    path: '/admin/auth/client-permissions',
    menu: 'admin',
    auth: true,
    description: 'Client Permissions page',
  },
  {
    name: 'User Roles',
    path: '/admin/auth/user-roles',
    menu: 'admin',
    auth: true,
    description: 'User Roles page',
  },
  {
    name: 'User Profiles',
    path: '/admin/auth/user-profiles',
    menu: 'admin',
    auth: true,
    description: 'User Profiles page',
  },
  {
    name: 'Ride Waiting',
    path: '/ride-waiting',
    menu: 'hidden',
    auth: true,
    description: 'Ride waiting page',
  },
  {
    name: 'Riders',
    path: '/riders',
    menu: 'hidden',
    auth: true,
    description: 'Near Riders page',
  },
  {
    name: 'Chats',
    path: '/chats',
    menu: 'hidden',
    auth: true,
    description: 'Chats page',
  },
  {
    name: 'Chatting',
    path: '/chats/[id]',
    menu: 'hidden',
    auth: true,
    description: 'Individual Chat page',
  },
  {
    name: 'Chat History',
    path: '/chats/histories',
    menu: 'hidden',
    auth: true,
    description: 'Chat History page',
  },
  {
    name: 'Payments Report',
    path: '/reports/payments',
    menu: 'report',
    auth: true,
    description: 'Payment report page',
  },
]

const permissions = [
  {
    description: 'Get All Users',
    route: '/api/auth/users',
    auth: true,
    name: 'Users',
    method: 'GET',
  },
  {
    description: 'Get User By Id',
    route: '/api/auth/users/:id',
    auth: true,
    name: 'Users',
    method: 'GET',
  },
  {
    description: 'Create User',
    route: '/api/auth/users',
    auth: true,
    name: 'Users',
    method: 'POST',
  },
  {
    description: 'Create User From Mobile',
    route: '/api/auth/users/register',
    auth: false,
    name: 'Users',
    method: 'POST',
  },
  {
    description: 'Update User',
    route: '/api/auth/users/:id',
    auth: true,
    name: 'Users',
    method: 'PUT',
  },
  {
    description: 'Delete User',
    route: '/api/auth/users/:id',
    auth: true,
    name: 'Users',
    method: 'DELETE',
  },
  {
    description: 'Login',
    route: '/api/auth/login',
    auth: false,
    name: 'Login',
    method: 'POST',
  },
  {
    description: 'OTP',
    route: '/api/auth/login/otp',
    auth: false,
    name: 'OTP',
    method: 'POST',
  },
  {
    description: 'Forgot Password',
    route: '/api/auth/forgot-password',
    auth: false,
    name: 'Forgot Password',
    method: 'POST',
  },
  {
    description: 'Reset Password',
    route: '/api/auth/reset-password',
    auth: false,
    name: 'Reset Password',
    method: 'POST',
  },
  {
    description: 'Get All User Profiles',
    route: '/api/auth/user-profiles',
    auth: true,
    name: 'User Profiles',
    method: 'GET',
  },
  {
    description: 'Get Profile',
    route: '/api/auth/profile',
    auth: true,
    name: 'User Profile',
    method: 'GET',
  },
  {
    description: 'Update Profile',
    route: '/api/auth/profile',
    auth: true,
    name: 'User Profile',
    method: 'POST',
  },
  {
    description: 'Get All Roles',
    route: '/api/auth/roles',
    auth: true,
    name: 'Roles',
    method: 'GET',
  },
  {
    description: 'Create Role',
    route: '/api/auth/roles',
    auth: true,
    name: 'Roles',
    method: 'POST',
  },
  {
    description: 'Update Role',
    route: '/api/auth/roles/:id',
    auth: true,
    name: 'Roles',
    method: 'PUT',
  },
  {
    description: 'Delete Role',
    route: '/api/auth/roles/:id',
    auth: true,
    name: 'Roles',
    method: 'DELETE',
  },
  {
    description: 'Get All Permissions',
    route: '/api/auth/permissions',
    auth: true,
    name: 'Permissions',
    method: 'GET',
  },
  {
    description: 'Create Permission',
    route: '/api/auth/permissions',
    auth: true,
    name: 'Permissions',
    method: 'POST',
  },
  {
    description: 'Update Permission',
    route: '/api/auth/permissions/:id',
    auth: true,
    name: 'Permissions',
    method: 'PUT',
  },
  {
    description: 'Delete Permission',
    route: '/api/auth/permissions/:id',
    auth: true,
    name: 'Permissions',
    method: 'DELETE',
  },
  {
    description: 'Get All User Roles',
    route: '/api/auth/user-roles',
    auth: true,
    name: 'User Roles',
    method: 'GET',
  },
  {
    description: 'Get User Roles By Id With POST',
    route: '/api/auth/user-roles/:id',
    auth: false,
    name: 'User Roles',
    method: 'POST',
  },
  {
    description: 'Create User Role',
    route: '/api/auth/user-roles',
    auth: true,
    name: 'User Roles',
    method: 'POST',
  },
  {
    description: 'Update User Role',
    route: '/api/auth/user-roles/:id',
    auth: true,
    name: 'User Roles',
    method: 'PUT',
  },
  {
    description: 'Delete User Role',
    route: '/api/auth/user-roles/:id',
    auth: true,
    name: 'User Roles',
    method: 'DELETE',
  },
  {
    description: 'Get All ClientPermissions',
    route: '/api/auth/client-permissions',
    auth: true,
    name: 'ClientPermissions',
    method: 'GET',
  },
  {
    description: 'Create Permission',
    route: '/api/auth/client-permissions',
    auth: true,
    name: 'ClientPermissions',
    method: 'POST',
  },
  {
    description: 'Update Permission',
    route: '/api/auth/client-permissions/:id',
    auth: true,
    name: 'ClientPermissions',
    method: 'PUT',
  },
  {
    description: 'Delete Permission',
    route: '/api/auth/client-permissions/:id',
    auth: true,
    name: 'ClientPermissions',
    method: 'DELETE',
  },
  {
    description: 'Get All Rides',
    route: '/api/rides',
    auth: true,
    name: 'Rides',
    method: 'GET',
  },
  {
    description: 'Create New Ride',
    route: '/api/rides',
    auth: true,
    name: 'Rides',
    method: 'POST',
  },
  {
    description: 'Delete Ride',
    route: '/api/rides/:id',
    auth: true,
    name: 'Rides',
    method: 'DELETE',
  },
  {
    description: 'Get Pending Rider',
    route: '/api/rides/pending',
    auth: true,
    name: 'Rides',
    method: 'GET',
  },
  {
    description: 'Get Near Riders',
    route: '/api/rides/near-riders',
    auth: true,
    name: 'Rides',
    method: 'POST',
  },
  {
    description: 'Get All Chats',
    route: '/api/chats',
    auth: true,
    name: 'Chats',
    method: 'GET',
  },
  {
    description: 'Get Chatting By Id',
    route: '/api/chats/:id',
    auth: true,
    name: 'Chats',
    method: 'GET',
  },
  {
    description: 'Create New Chat',
    route: '/api/chats',
    auth: true,
    name: 'Chats',
    method: 'POST',
  },
  {
    description: 'Update Chat',
    route: '/api/chats/:id',
    auth: true,
    name: 'Chats',
    method: 'PUT',
  },
  {
    description: 'Delete Chat',
    route: '/api/chats/:id',
    auth: true,
    name: 'Chats',
    method: 'DELETE',
  },
  {
    description: 'Get Chat History By Id',
    route: '/api/chats/histories',
    auth: true,
    name: 'Chats',
    method: 'GET',
  },
  {
    description: 'Verify Payment Transactions From Merchant',
    route: '/api/payments',
    auth: true,
    name: 'Payments',
    method: 'POST',
  },
  {
    description: 'Get Payments Report',
    route: '/api/reports/payments',
    auth: true,
    name: 'Payments Report',
    method: 'POST',
  },
  {
    description: 'Get Payments Transaction Report',
    route: '/api/reports/payments/transactions',
    auth: true,
    name: 'Payments Transaction Report',
    method: 'GET',
  },
  {
    description: 'Plate Check',
    route: '/api/rides/plate',
    auth: true,
    name: 'Plate Check',
    method: 'POST',
  },
]

export { roles, users, profile, permissions, clientPermissions }
